### ISSUE TITLE
Random sample order

### ISSUE THREAD

**Issue by nnbveh** [brian3kb/digichain#1]
Hi Brian! Thanks for the great tool first of all. Now, would it be possible to add an option to place the samples in random order when creating a chain? Like if i'm importing a bunch of kicks from machine drum, AR, pulsar, they're all going to be grouped somehow, by the name or by the order imported right? It would be nice to have an option to mix them all up to get some more inspiration ;)

Looks like you already have some sort of randomization library in your github, maybe you could just use it for this somehow...

Thanks!

**Comment by brian3kb** [comment]
Thanks for the feedback - but this is already implemented.

Option 1:
If you already have samples loaded into the list, hold the Shift key on your keyboard, and click the 'RESET SORT/ORDER' button (it will turn blue while the shift key is down), this will randomize the list.

Option 2:
With an empty list, first choose a chain length (e.g. click the '64' button).
Now, while holding down the Shift key on your keyboard, drag in a folder (or folders) containing samples.
Keep the shift key held down until after you have dropped in the folders/files.
DigiChain will randomly select the number of samples to fill the chain length from the dropped files, so you'll get a different chain on each drop.

Hopefully one of those approaches does the trick!
