### ISSUE TITLE
Sample Edit View: Multiple Looped Playbacks

### ISSUE THREAD

**Issue by dijksterhuis** [brian3kb/digichain#2]
1. Load samples.
2. Go to edit a sample start / end position.
3. Click on looped playback more than once

Now multiple instances of looped playback for that sample.

The stop button stops the looped playback of the last started playback loop. To kill all the loops have to keep clicking stop until all loops are stopped.

On latest MS Store version -- downloaded today (not sure how to check the versioning within an MS Store app, I'm a `make && make install` kind of guy).

**Comment by brian3kb** [comment]
Thanks for the feedback! I'll look at these over the weekend as it's going tk be a busy work week 🙂

There a small version number in the bottom right of the screen, and in the about pop-up when clicking the ( i ) icon that's also down there.

If the MS Store version isn't at the latest GitHub released version, right-click on the screen and choose Refresh from the options. Edge doesn't always refresh latest when there's an internet connection if running in the store apps sandbox.

**Comment by dijksterhuis** [comment]
Will check the version when I boot back into windows -- busy work week for myself as well ;)

**Comment by dijksterhuis** [comment]
Also I did want to say that the "here's your samples in rows and you can edit one after the other and dump out in sliced chains" felt like an awesome workflow.

Spent like 3 hours fiddling around with chains on Saturday night :+1: much nicer than loading samples into separate DAW tracks, editing, bouncing then chaining!

**Comment by brian3kb** [comment]
Fix deployed with v1.4.7 release. Please do feel free to re-open if needed - thanks again for reporting, and also for using the web app :)
