### ISSUE TITLE
Sample Edit View: Creating then removing Slice sets end point = 0

### ISSUE THREAD

**Issue by dijksterhuis** [brian3kb/digichain#3]
1. Load a sample
2. Go to edit a sample
2. With whole sample waveform selected (default) -- create a new slice (Slice 1)
3. Remove the slice without any further changes

Once the slice is removed the time markers for start/end will be at `0`/`0` position instead of `0`/`sample_end`

Might be by design, but seemed a bit off as nothing is changed with the waveform (no cropping / etc).

Can reselect who waveform with the ALL button, but adds an extra mouse click just to get back to original waveform selection state (before slice add --> delete).

**Comment by brian3kb** [comment]
Fix deployed with v1.4.7 release.
