### ISSUE TITLE
Duplicating Samples: Uses original upload name (not an updated name)

### ISSUE THREAD

**Issue by dijksterhuis** [brian3kb/digichain#4]
Duplicating readds the old file name instead of the name currently in use for the parent sample,

First sample was the original with a new name

Second sample was duplicated via the UI.

![image](https://github.com/brian3kb/digichain/assets/11841332/7bb56445-92fa-4fdd-b7ef-bbd05fc328dd)

Doing a fair bit of copy/pasting/editing with names just to make sure I'm tracking modified samples.

**Comment by brian3kb** [comment]
Fix deployed with v1.4.7 release.
